{
  "openapi": "3.0.0",
  "info": {
    "title": "Loans",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/loans/{loanId}": {
      "parameters": [
        {
          "schema": {
            "type": "integer"
          },
          "name": "loanId",
          "in": "path",
          "required": true,
          "description": "Id of an existing loan."
        }
      ],
      "get": {
        "summary": "Get loan Info by loan ID",
        "tags": [],
        "responses": {
          "200": {
            "description": "loan Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/loan"
                },
                "examples": {
                  "Get loan Alice Smith": {
                    "value": {
                      "id": 142,
                      "firstName": "Alice",
                      "lastName": "Smith",
                      "email": "alice.smith@gmail.com",
                      "dateOfBirth": "1997-10-31",
                      "emailVerified": true,
                      "signUpDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "loan Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "$ref": "https://component-library.pstmn-beta.io/component/1a88ac3c-3146-4260-afc8-6f7d02b0cca1"
                    },
                    "_trackId": {
                      "type": "string"
                    }
                  }
                },
                "examples": {}
              }
            }
          }
        },
        "operationId": "get-loans-loanId",
        "description": "Retrieve the information of the loan with the matching loan ID."
      },
      "patch": {
        "summary": "Update loan Information",
        "operationId": "patch-loans-loanId",
        "responses": {
          "200": {
            "description": "loan Updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/loan"
                },
                "examples": {
                  "Updated loan Rebecca Baker": {
                    "value": {
                      "id": 13,
                      "firstName": "Rebecca",
                      "lastName": "Baker",
                      "email": "rebecca@gmail.com",
                      "dateOfBirth": "1985-10-02",
                      "emailVerified": false,
                      "createDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "loan Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "$ref": "https://component-library.pstmn-beta.io/component/1a88ac3c-3146-4260-afc8-6f7d02b0cca1"
                    },
                    "_trackId": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "description": "Update the information of an existing loan.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "description": "If a new email is given, the loan's email verified property will be set to false."
                  },
                  "dateOfBirth": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Update First Name": {
                  "value": {
                    "firstName": "Rebecca"
                  }
                },
                "Update Email": {
                  "value": {
                    "email": "rebecca@gmail.com"
                  }
                },
                "Update Last Name & Date of Birth": {
                  "value": {
                    "lastName": "Baker",
                    "dateOfBirth": "1985-10-02"
                  }
                }
              }
            }
          },
          "description": "Patch loan properties to update."
        }
      }
    },
    "/loan": {
      "post": {
        "summary": "Create New loan",
        "operationId": "post-loan",
        "responses": {
          "200": {
            "description": "loan Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/loan"
                },
                "examples": {
                  "New loan Bob Fellow": {
                    "value": {
                      "id": 12,
                      "firstName": "Bob",
                      "lastName": "Fellow",
                      "email": "bob.fellow@gmail.com",
                      "dateOfBirth": "1996-08-24",
                      "emailVerified": false,
                      "createDate": "2020-11-18"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing Required Information"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "dateOfBirth": {
                    "type": "string",
                    "format": "date"
                  }
                },
                "required": [
                  "firstName",
                  "lastName",
                  "email",
                  "dateOfBirth"
                ]
              },
              "examples": {
                "Create loan Bob Fellow": {
                  "value": {
                    "firstName": "Bob",
                    "lastName": "Fellow",
                    "email": "bob.fellow@gmail.com",
                    "dateOfBirth": "1996-08-24"
                  }
                }
              }
            }
          },
          "description": "Post the necessary fields for the API to create a new loan."
        },
        "description": "Create a new loan."
      }
    }
  },
  "components": {
    "schemas": {
      "loan": {
        "title": "loan",
        "type": "object",
        "description": "",
        "x-examples": {
          "Alice Smith": {
            "id": 142,
            "firstName": "Alice",
            "lastName": "Smith",
            "email": "alice.smith@gmail.com",
            "dateOfBirth": "1997-10-31",
            "emailVerified": true,
            "signUpDate": "2019-08-24"
          }
        },
        "properties": {
          "id": {
            "type": "integer",
            "description": "Unique identifier for the given loan."
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "dateOfBirth": {
            "type": "string",
            "format": "date",
            "example": "1997-10-31"
          },
          "emailVerified": {
            "type": "boolean",
            "description": "Set to true if the loan's email has been verified."
          },
          "createDate": {
            "type": "string",
            "format": "date",
            "description": "The date that the loan was created."
          }
        },
        "required": [
          "id",
          "firstName",
          "lastName",
          "email",
          "emailVerified"
        ]
      }
    }
  }
}